stages:
  - test
  - version-bump

run_tests:
  rules:
    - if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'AUTOMATIC VERSION BUMP') }}
  image: node:18-alpine3.17
  before_script:
    - npm i jest@29.7.0
  script:
    - npm test

version_bump:
  rules:
    - if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'AUTOMATIC VERSION BUMP')
  image: node:18-buster
  stage: version-bump
  before_script:
    - yarn add webpack@5.89.0
    - apt-get update -qy 
    - apt-get install -y jq
  script:
    - npm version patch --git-tag-version false
    - PACKAGE_JSON_FILE=$(cat package.json)
    - PACKAGE_VERSION=$(echo "$PACKAGE_JSON_FILE" | jq -r '.version')
    - VAR_TIME=$(date '+%Y-%m-%d')
    - |
      API_RESPONSE=$(curl --request GET "https://api.github.com/repos/sebastian-meckovski/Seb-Storybook/pulls?state=closed" \
        --header "PRIVATE-TOKEN: ${{ secrets.AUTO_VERSION_TOKEN }}")
      FIRST_MERGE_REQUEST=$(echo "$API_RESPONSE" | jq -r '.[0]')
      DESCRIPTION=$(echo "$FIRST_MERGE_REQUEST" | jq -r '.description')
      AUTHOR=$(echo "$FIRST_MERGE_REQUEST" | jq -r '.user.login')
      TARGET_BRANCH=$(echo "$FIRST_MERGE_REQUEST" | jq -r '.base.ref')
      PR_URL=$(echo "$FIRST_MERGE_REQUEST" | jq -r '.html_url')
      TITLE=$(echo "$FIRST_MERGE_REQUEST" | jq -r '.title')
      sed -i "2i - Author: ${AUTHOR}" CHANGELOG.md
      sed -i "2i - Pull request URL: ${PR_URL}" CHANGELOG.md
      sed -i "2i - Target branch: ${TARGET_BRANCH}" CHANGELOG.md
      sed -i "2i - Description: ${DESCRIPTION}" CHANGELOG.md
      sed -i "2i - Title: ${TITLE}" CHANGELOG.md
      sed -i "2i ## ${PACKAGE_VERSION} (${VAR_TIME})" CHANGELOG.md
      sed -i "2i \ " CHANGELOG.md
    - git config user.email "sebastian.meckovski@gmail.com"
    - git config user.name "Sebastian Meckovski"
    - git remote set-url origin https://${{ secrets.AUTO_VERSION_TOKEN }}@github.com/sebastian-meckovski/Seb-Storybook.git
    - git add .
    - git commit -m "AUTOMATIC VERSION BUMP"
    - git push origin HEAD:$CI_DEFAULT_BRANCH
    - echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
    - npm build
    - npm publish